#!/bin/sh

TARGET="master"

source deployment/settings || exit 1
source "deployment/settings.$TARGET" || exit 1

dbName=apostrophesandbox

remoteDbName=new-demo-master

#Enter the Project name (should be what you called it for stagecoach).
projectName=$PROJECT

#Enter the SSH username/url for the remote server.
remoteSSH=$USER@$SERVER

echo "Syncing MongoDB"
ssh $remoteSSH mongodump -d $remoteDbName -o /tmp/mongodump.$dbName &&
rsync -av $remoteSSH:/tmp/mongodump.$dbName/ /tmp/mongodump.$dbName  &&
ssh $remoteSSH rm -rf /tmp/mongodump.$dbName &&
mongorestore --drop -d $dbName /tmp/mongodump.$dbName/$dbName &&
echo "Syncing Files" &&
rsync -av --delete $remoteSSH:/opt/stagecoach/apps/$projectName/uploads/ ./public/uploads  &&
echo "Synced down from $TARGET"
