#!/bin/sh

TARGET="$1"
if [ -z "$TARGET" ]; then
  echo "Usage: ./scripts/sync-down production"
  echo "(or as appropriate)"
  exit 1
fi

source deployment/settings || exit 1
source "deployment/settings.$TARGET" || exit 1

dbName=$PROJECT

#Enter the SSH username/url for the remote server.
remoteSSH=$USER@$SERVER

echo "Syncing MongoDB"
ssh $remoteSSH mongodump -d $dbName -o /tmp/mongodump.$dbName &&
rsync -av $remoteSSH:/tmp/mongodump.$dbName/ /tmp/mongodump.$dbName  &&
ssh $remoteSSH rm -rf /tmp/mongodump.$dbName &&
mongorestore --drop -d apostrophesandbox /tmp/mongodump.$dbName/$dbName &&
echo "Syncing Files" &&
rsync -av --delete $remoteSSH:/opt/stagecoach/apps/client-demo/uploads/ ./public/uploads  &&
echo "Synced down from $TARGET"

# POSSIBLE SOLUTION WITH FORWARDS/BACKWARDS MONGODB COMPATIBILITY
#
# Just the dump logic so far:
#
#mongo --quiet mydatabase --eval "db.getCollectionNames().join('\n')" | \
#grep -v system.indexes | \
#xargs -L 1 -I {} mongoexport -d mydatabase -c {} --out {}.json
